// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2OJvtPQ9ORwpqMC0_g7WIowu9Ye0vUh8',
    appId: '1:913252198026:android:f23d83fed6cda5d2d6ef73',
    messagingSenderId: '913252198026',
    projectId: 'myapp-da59c',
    authDomain: 'myapp-da59c.firebaseapp.com',
    storageBucket: 'myapp-da59c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2OJvtPQ9ORwpqMC0_g7WIowu9Ye0vUh8',
    appId: '1:913252198026:android:f23d83fed6cda5d2d6ef73',
    messagingSenderId: '913252198026',
    projectId: 'myapp-da59c',
    storageBucket: 'myapp-da59c.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2OJvtPQ9ORwpqMC0_g7WIowu9Ye0vUh8',
    appId: '1:913252198026:android:f23d83fed6cda5d2d6ef73',
    messagingSenderId: '913252198026',
    projectId: 'myapp-da59c',
    authDomain: 'myapp-da59c.firebaseapp.com',
    storageBucket: 'myapp-da59c.firebasestorage.app',
  );
}
